### PR TITLE
First round of improvements around non-nullability

### PR DESCRIPTION
**Pull request by rbino**
First round of implementation of what was discussed in #105 

This PR makes result types non-nullable.

### CODE REVIEW

**Comment by zachdaniel** [comment]
For the ids in updates being non nullable, that would be a breaking change for any queries people have, right? I think we'll have to put that behind a configuration for now, and undo it when we do 1.0 for this library.

**Comment by rbino** [comment]
Wouldn't the same thing that was discussed in #105 regarding making the input non-nullable apply (see below)?

> It would be a breaking change to require it, even if we only did it in cases where there was at least one required input inside of it, because nullable -> not nullable on an input type is theoretically breaking. Although in those scenarios the action would fail 100% of the time... 🤷 so maybe fine to just make both changes.

Anyway, adding a config works for me too, but which kind of config (i.e. at what level) should it be?

**Comment by zachdaniel** [comment]
Yeah, but the changes you made in the test made me realize that it's not enough that it wouldn't have worked, because it will break people's type declarations. i.e if they have `id: ID` `GraphQL` will yell at them because its not an optional value anymore. We can use application config, there should be some other examples in this repo. I'll cut a 1.0 around the time we do 3.0 of Ash (1-2 months)

**Comment by rbino** [comment]
@zachdaniel I've left only the non-breaking result change in this PR and I'll do a separate one with IDs and input objects behind an application config

**Review by zachdaniel — APPROVED** [review]

**Pull request merged**
