### PR TITLE
Data layer functions

### PR DESCRIPTION
**Pull request by barnabasJ**
Allow DataLayer Filters (like, ilike from postgres in filter) 

depends on 
* https://github.com/ash-project/ash_postgres/pull/205
* https://github.com/ash-project/ash/pull/874

Very naive first implementation. It works in my project already, but I feel I'm probably missing some edge cases.
Somehow, the filter is already only applied to String attributes, but I'm not completely sure why.

### CODE REVIEW

**Comment by zachdaniel** [comment]
(Thats why it knows what types to support)

**Comment by zachdaniel** [comment]
Okay, maybe not 😆 I’m not sure how it could only be supporting strings. I think the function variation will need to do something similar to what the operator code does. In fact, ideally they’d share the same code instead of branching.

**Review by zachdaniel — APPROVED** [review]

**Comment by barnabasJ** [comment]
> Is this good to go?

Everything is fine from my side.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
