### PR TITLE
Implement AshGraphql.Error for Ash.Error.Query.ReadActionRequiresActor

### PR DESCRIPTION
**Pull request by col**
### Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

### CODE REVIEW

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
LGTM, let me know when it's no longer a draft.

**Comment by col** [comment]
> LGTM, let me know when it's no longer a draft.

I was going to try to create a test for it but maybe it's not required in this case.

**Comment by zachdaniel** [comment]
Yeah, I guess a test would be warranted. Easiest way would be to add an action with the require actor change and assert an error response.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
